name: Publish Package
on:
  push:
    branches:
      interfolio/ng-zorro-antd

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm install
      - run: npm run build:lib
      - run: npm run update:package
      - run: npm publish --access=public publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
